"""add thumbnail column to event table

Revision ID: 3993cb6adbee
Revises: 018d8c71599d
Create Date: 2025-05-21 20:36:16.366439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3993cb6adbee'
down_revision = '018d8c71599d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_event', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=256), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_stadium', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stadium', ['stadium_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_constraint('fk_weather_stadium', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stadium', ['stadium_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_weather_stadium', 'stadium', ['stadium_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_review_stadium', 'stadium', ['stadium_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('thumbnail')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_booking_event', 'event', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
