"""add seat_no and stand to booking

Revision ID: 54b588e0044c
Revises: a1e7fbceaedc
Create Date: 2025-05-16 04:52:04.410745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b588e0044c'
down_revision = 'a1e7fbceaedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_no', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stand', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('stand')
        batch_op.drop_column('seat_no')

    # ### end Alembic commands ###
