"""Add missing columns to stadium table

Revision ID: 7c86e25802a6
Revises: 3c30da8c246d
Create Date: 2025-05-16 03:57:53.394646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c86e25802a6'
down_revision = '3c30da8c246d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'ticket' in inspector.get_table_names():
        op.drop_table('ticket')

    if 'newsletter_subscriber' in inspector.get_table_names():
        with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
            batch_op.drop_index('email')
        op.drop_table('newsletter_subscriber')

    if 'time_slot_booking' in inspector.get_table_names():
        op.drop_table('time_slot_booking')

    event_columns = [col['name'] for col in inspector.get_columns('event')]
    with op.batch_alter_table('event', schema=None) as batch_op:
        if 'name' not in event_columns:
            batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        if 'category_id' not in event_columns:
            batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        if 'price' not in event_columns:
            batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        # Ensure time_slot_id is nullable before updating values
        if 'time_slot_id' in event_columns:
            batch_op.alter_column('time_slot_id', existing_type=mysql.INTEGER(), nullable=True)
        if 'total_tickets' in event_columns:
            batch_op.drop_column('total_tickets')
        if 'category' in event_columns:
            batch_op.drop_column('category')
        if 'ticket_price' in event_columns:
            batch_op.drop_column('ticket_price')
        if 'title' in event_columns:
            batch_op.drop_column('title')
        if 'additional_services' in event_columns:
            batch_op.drop_column('additional_services')
        if 'event_type' in event_columns:
            batch_op.drop_column('event_type')
        if 'image_url' in event_columns:
            batch_op.drop_column('image_url')

    # Insert a dummy category with id=1 if it does not exist
    if 'category' in inspector.get_table_names():
        result = conn.execute(sa.text("SELECT id FROM category WHERE id=1")).fetchone()
        if not result:
            conn.execute(sa.text("INSERT INTO category (id, name) VALUES (1, 'General')"))
        # Set all event.category_id values to 1 before adding the foreign key constraint
        op.execute("UPDATE event SET category_id = 1")

    stadium_columns = [col['name'] for col in inspector.get_columns('stadium')]
    with op.batch_alter_table('stadium', schema=None) as batch_op:
        if 'price_per_hour' not in stadium_columns:
            batch_op.add_column(sa.Column('price_per_hour', sa.Float(), nullable=False))
        if 'contact_info' not in stadium_columns:
            batch_op.add_column(sa.Column('contact_info', sa.String(length=100), nullable=True))
        if 'latitude' not in stadium_columns:
            batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        if 'longitude' not in stadium_columns:
            batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # Now insert the dummy stadium (after all columns exist)
    result = conn.execute(sa.text("SELECT id FROM stadium WHERE id=1")).fetchone()
    if not result:
        # Only use columns that exist in the stadium table
        columns = [col['name'] for col in inspector.get_columns('stadium')]
        values = []
        insert_cols = []
        if 'id' in columns:
            insert_cols.append('id')
            values.append('1')
        if 'name' in columns:
            insert_cols.append('name')
            values.append("'Dummy Stadium'")
        if 'location' in columns:
            insert_cols.append('location')
            values.append("'N/A'")
        if 'capacity' in columns:
            insert_cols.append('capacity')
            values.append('0')
        if 'facilities' in columns:
            insert_cols.append('facilities')
            values.append("'[]'")
        if 'image_url' in columns:
            insert_cols.append('image_url')
            values.append("''")
        if 'price_per_hour' in columns:
            insert_cols.append('price_per_hour')
            values.append('0.0')
        if 'contact_info' in columns:
            insert_cols.append('contact_info')
            values.append("''")
        if 'latitude' in columns:
            insert_cols.append('latitude')
            values.append('NULL')
        if 'longitude' in columns:
            insert_cols.append('longitude')
            values.append('NULL')
        insert_stmt = f"INSERT INTO stadium ({', '.join(insert_cols)}) VALUES ({', '.join(values)})"
        conn.execute(sa.text(insert_stmt))

    time_slot_columns = [col['name'] for col in inspector.get_columns('time_slot')]
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        if 'time_slot_ibfk_2' in [fk['name'] for fk in inspector.get_foreign_keys('time_slot')]:
            batch_op.drop_constraint('time_slot_ibfk_2', type_='foreignkey')
        if 'stadium_id' in time_slot_columns:
            batch_op.drop_column('stadium_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)

    # Ensure a time_slot with id=1 exists before updating event rows
    result = conn.execute(sa.text("SELECT id FROM time_slot WHERE id=1")).fetchone()
    if not result:
        # Only use columns that exist in the time_slot table
        columns = [col['name'] for col in inspector.get_columns('time_slot')]
        values = []
        insert_cols = []
        if 'id' in columns:
            insert_cols.append('id')
            values.append('1')
        if 'stadium_id' in columns:
            insert_cols.append('stadium_id')
            values.append('1')
        if 'start_time' in columns:
            insert_cols.append('start_time')
            values.append("'2000-01-01 00:00:00'")
        if 'end_time' in columns:
            insert_cols.append('end_time')
            values.append("'2000-01-01 01:00:00'")
        insert_stmt = f"INSERT INTO time_slot ({', '.join(insert_cols)}) VALUES ({', '.join(values)})"
        conn.execute(sa.text(insert_stmt))
    # Update existing rows with NULL time_slot_id to a valid value (e.g., 1)
    op.execute("UPDATE event SET time_slot_id = 1 WHERE time_slot_id IS NULL")
    # Now make the column NOT NULL
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('time_slot_id', existing_type=sa.Integer(), nullable=False)
        # Now add the foreign key constraint for category_id
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stadium_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('time_slot_ibfk_2', 'stadium', ['stadium_id'], ['id'])

    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('contact_info')
        batch_op.drop_column('price_per_hour')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('event_type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('additional_services', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('ticket_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('total_tickets', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('time_slot_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('category_id')
        batch_op.drop_column('name')

    op.create_table('time_slot_booking',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_slot_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('event_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('additional_services', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='time_slot_booking_ibfk_1'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slot.id'], name='time_slot_booking_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('newsletter_subscriber',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('subscribed_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('ticket',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seat_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('purchase_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], name='ticket_ibfk_1'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='ticket_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
