"""add total_tickets to event table

Revision ID: a1e7fbceaedc
Revises: fe6eff0d0822
Create Date: 2025-05-16 04:17:22.253055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e7fbceaedc'
down_revision = 'fe6eff0d0822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tickets', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('total_tickets')

    # ### end Alembic commands ###
